### ISSUE TITLE
Infra(OS): `bugs` to Ubuntu 24.04

### ISSUE THREAD

**Issue by JacobCoffee** [python/psf-salt#419]
```[tasklist]
### Tasks
- [x] Changeset tested against host set to default (jammy)
- [x] Changeset tested against host set to noble
- [x] Data migrated
- [x] VM provisioned
- [x] DNS records updated
```

**Comment by JacobCoffee** [comment]
This was closed by accident, it was just moved under the LB

**Comment by JacobCoffee** [comment]
Blocked by roundup on 2.7
