### ISSUE TITLE
Infra(OS): `pythontest` to Ubuntu 24.04

### ISSUE THREAD

**Issue by JacobCoffee** [python/psf-salt#423]
```[tasklist]
### Tasks
- [x] Changeset tested against host set to default (jammy)
- [x] Changeset tested against host set to noble
- [x] VM upgraded
- [x] ~Data transferred~ No backups done on this service
- [ ] https://github.com/python/cpython/issues/122795
```

No changes required besides base changes

**Comment by JacobCoffee** [comment]
Completely refreshed the 24.04 droplet, but still getting some strange errors like NGINX not installing which does not even happen locally...

**Comment by JacobCoffee** [comment]
```
root@pythontest-2404:~# sudo dpkg --configure -a
root@pythontest-2404:/home/psf-users/coffee# apt install nginx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  datadog-agent
Recommended packages:
  datadog-signing-keys
The following NEW packages will be installed:
  nginx
The following packages will be upgraded:
  datadog-agent
1 upgraded, 1 newly installed, 0 to remove and 39 not upgraded.
1 not fully installed or removed.
Need to get 0 B/301 MB of archives.
After this operation, 1,453 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
```

I wonder if adding `- pkg: datadog-signing-keys` to `datadog/init.sls` is a good idea?

**Comment by JacobCoffee** [comment]
> I wonder if adding - pkg: datadog-signing-keys to datadog/init.sls is a good idea?

I think so... NGINX properly installed after we fixed the datadog agent keys issue by installing that package:
```
root@pythontest-2404:~# sudo dpkg --configure -a
root@pythontest-2404:~# apt install datadog-signing-keys
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  datadog-agent
The following NEW packages will be installed:
  datadog-signing-keys
The following packages will be upgraded:
  datadog-agent
1 upgraded, 1 newly installed, 0 to remove and 39 not upgraded.
1 not fully installed or removed.
Need to get 0 B/300 MB of archives.
After this operation, 1,450 MB of additional disk space will be used.
Do you want to continue? [Y/n]
(Reading database ... 83500 files and directories currently installed.)
Preparing to unpack .../datadog-agent_1%3a6.53.0-1_amd64.deb ...
Unpacking datadog-agent (1:6.53.0-1) over (1:6.53.0-1) ...
Selecting previously unselected package datadog-signing-keys.
Preparing to unpack .../datadog-signing-keys_1%3a1.3.1-1_all.deb ...
Unpacking datadog-signing-keys (1:1.3.1-1) ...
Setting up datadog-agent (1:6.53.0-1) ...
Creating dd-agent group
Creating dd-agent user
Enabling service datadog-agent
Created symlink /etc/systemd/system/multi-user.target.wants/datadog-agent.service → /usr/lib/systemd/system/datadog-agent.service.
Created symlink /etc/systemd/system/multi-user.target.wants/datadog-agent-process.service → /usr/lib/systemd/system/datadog-agent-process.service.
Created symlink /etc/systemd/system/multi-user.target.wants/datadog-agent-trace.service → /usr/lib/systemd/system/datadog-agent-trace.service.
Created symlink /etc/systemd/system/multi-user.target.wants/datadog-agent-security.service → /usr/lib/systemd/system/datadog-agent-security.service.
No datadog.yaml file detected, not starting the agent
Setting up datadog-signing-keys (1:1.3.1-1) ...
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.

root@pythontest-2404:~# sudo salt-call state.highstate

Summary for local
--------------
Succeeded: 156 (changed=18)
Failed:      0
```

**Comment by JacobCoffee** [comment]
I am at this part on the migration guide:
https://infra.psf.io/guides/migration-recipe.html#stop-services-on-old-host

Waiting for Ee to get back before proceeding because I can't remember the changes need in CPython to test our test runners to the new host
